spring:
  config:
    import: optional:application-secrets.yaml

  datasource:
    url: jdbc:h2:mem:incidentdb
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always

